version: '3.9'

services:
  web:
    build:
      context: .
      target: dependencies
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev